// Self-serve API key store (PRD P2-1 — Paid DaaS tier).
//
// There is no database wired for mymcptools yet, so this follows the same
// committed-JSON pattern already used for the trust dataset itself
// (src/data/probe-status.json / status-store.ts): keys purchased via the
// /developers self-serve checkout are generated by the Stripe webhook and
// emailed to both the customer and admin, and admin appends the record here
// (src/data/api-keys.json) + redeploys to activate it — mirroring the exact
// "Set sponsored: true ... in probe-inventory.json" fulfillment pattern used
// for Featured/Sponsored listings. A real DB (Supabase/Postgres) would remove
// this manual step; tracked as a P2 follow-up, not required to ship the tier.

import rawKeys from "@/data/api-keys.json";

export interface ApiKeyRecord {
  key: string;
  email: string;
  plan: string;
  created_at: string;
  status: "active" | "revoked";
}

interface KeyStore {
  keys: ApiKeyRecord[];
}

const store = rawKeys as KeyStore;

const activeKeys = new Set(
  store.keys.filter((k) => k.status === "active").map((k) => k.key)
);

/** True if `key` is a committed, active self-serve key. */
export function isActiveStoredKey(key: string): boolean {
  return activeKeys.has(key);
}

/** All committed key records (do not mutate). */
export function allStoredKeys(): readonly ApiKeyRecord[] {
  return store.keys;
}
