/**
 * THE DOOR FROM A SERVER PAGE TO THE $49/mo TRUST DATA API.
 *
 * WHERE THE DEMAND WAS (measured 2026-10-03, analytics.events, 30 days, not
 * is_bot). The paid tier's whole funnel — 401 upgrade bodies, free-tier
 * pointers, the keyless trial, the GET checkout — is machine-facing, and its
 * real cohort is ~1 caller a month: 2 non-crawler callers reached a key gate
 * in 30 days, one of them our own curl. Meanwhile 1,533 human sessions read
 * this site, 694 of them on /servers/[slug], where every page renders a Trust
 * verdict built from exactly the signals the API sells. /developers — the only
 * page that names the price — drew 2 sessions. No server page linked to it:
 * the one link in the verdict block went to /trust ("How grades are
 * computed"), which carries no price either. So the 694 readers best placed to
 * want the dataset had no route to the one priced surface on the property.
 *
 * This module is the pure half: what we can truthfully say we hold for THIS
 * server, the catalog-wide coverage (generated by pro-offer, never typed), and
 * an attributed href so the arrival is countable in the pageview beacon
 * (utm_source=server-page) — read with `npm run demand:report`.
 *
 * Rules, enforced by `npm run door:selfcheck`:
 *   1. A fact appears in `heldHere` only if a store holds it for this slug.
 *   2. Coverage comes from sellableCapabilities(); zero-row capabilities
 *      ("uptime") can never be named.
 *   3. The price comes from PRO_PRICE_USD, the same constant the 401 body uses.
 */
import { PRO_PRICE_USD } from "@/lib/api/auth";
import { serverPageCheckoutAction } from "@/lib/api/checkout-entry";
import { PASS_DAYS, PASS_PRICE_USD } from "@/lib/api/pass";
import {
  proPopulation,
  sellableCapabilities,
  type ProCapabilityId,
} from "@/lib/api/pro-offer";
import { getInstallCheck } from "@/lib/trust/install-check";
import { getStaticSignal } from "@/lib/trust/static-signals-store";
import { getStatus } from "@/lib/trust/status-store";

export const DOOR_UTM_SOURCE = "server-page";
export const DOOR_UTM_MEDIUM = "trust-verdict";

export interface HeldFact {
  capability: ProCapabilityId;
  /** Plain-language statement of what we hold for this server. */
  text: string;
}

export interface ServerApiDoor {
  /**
   * The buy button's form action: POST /api/trust-api/checkout
   * ?from=server-page&server=<slug> -> 303 to Stripe. One press, one hop.
   */
  checkoutAction: string;
  /**
   * The $9 one-time 30-day key (src/lib/api/pass.ts): same form, `&plan=pass`.
   * 0 of 33 exposed sessions pressed $49/mo; the property's only stranger
   * payment ever was a one-time $9.
   */
  passAction: string;
  passPriceUsd: number;
  passDays: number;
  /** /developers#pro (what the feed holds), attributed to this page. */
  href: string;
  /** This server's row in the free per-server endpoint (no key). */
  freeJsonHref: string;
  priceUsd: number;
  population: number;
  /** Facts the paid feed carries for this specific server. Never padded. */
  heldHere: HeldFact[];
  /** Catalog-wide coverage, widest first, generated from the stores. */
  coverage: { label: string; rows: number }[];
}

function isoDay(d: string | null | undefined): string | null {
  if (!d) return null;
  const t = new Date(d);
  return Number.isNaN(t.getTime()) ? null : t.toISOString().slice(0, 10);
}

export function serverApiDoorHref(slug: string): string {
  const qs = new URLSearchParams({
    utm_source: DOOR_UTM_SOURCE,
    utm_medium: DOOR_UTM_MEDIUM,
    utm_campaign: slug,
  });
  return `/developers?${qs.toString()}#pro`;
}

export function serverApiDoor(slug: string): ServerApiDoor {
  const heldHere: HeldFact[] = [];

  const ic = getInstallCheck(slug);
  if (ic) {
    heldHere.push({
      capability: "install_signal",
      text: ic.exists
        ? `${ic.registry} package ${ic.packageName} verified to exist (checked ${ic.checkedAt})`
        : `install command names ${ic.packageName}, which does not exist on ${ic.registry} (checked ${ic.checkedAt})`,
    });
  }

  const ss = getStaticSignal(slug);
  const commit = isoDay(ss?.last_commit_at);
  const release = isoDay(ss?.last_release_at);
  if (commit || release) {
    heldHere.push({
      capability: "static_signal",
      text: [commit && `last commit ${commit}`, release && `last release ${release}`]
        .filter(Boolean)
        .join(", "),
    });
  }

  const st = getStatus(slug);
  if (st && st.latency_ms != null) {
    heldHere.push({
      capability: "live_status",
      text: `live MCP handshake: ${st.verdict}, ${st.latency_ms} ms`,
    });
  }

  // Only capabilities that are sellable at all may be claimed per-server.
  const sellable = new Set(sellableCapabilities().map((c) => c.id));

  return {
    checkoutAction: serverPageCheckoutAction(slug),
    passAction: serverPageCheckoutAction(slug, "pass"),
    passPriceUsd: PASS_PRICE_USD,
    passDays: PASS_DAYS,
    href: serverApiDoorHref(slug),
    freeJsonHref: `/api/v1/servers/${encodeURIComponent(slug)}/status`,
    priceUsd: PRO_PRICE_USD,
    population: proPopulation(),
    heldHere: heldHere.filter((f) => sellable.has(f.capability)),
    coverage: sellableCapabilities().map((c) => ({ label: c.label, rows: c.rows })),
  };
}
