// Read-side accessor for the committed firewall corpus
// (src/data/firewall-corpus.json), regenerated by scripts/firewall-sweep.mts.
//
// Static import, matching the static-signals-store convention: the file is
// committed, so reads are fast and allocation-free and the build can prerender
// the /firewall page from it.

import rawStore from '@/data/firewall-corpus.json';
import type {
  CorpusEntry,
  CorpusStore,
  Ecosystem,
  PackageVerdict,
} from '@/lib/firewall/types';

const store = rawStore as unknown as CorpusStore;

const byKey = new Map<string, CorpusEntry>(
  store.entries.map((e) => [`${e.ecosystem}:${e.name}`, e])
);

/** A corpus row for an exact (ecosystem, name), or undefined. */
export function getCorpusEntry(
  name: string,
  ecosystem: Ecosystem
): CorpusEntry | undefined {
  return byKey.get(`${ecosystem}:${name}`);
}

/** When the committed corpus was generated. */
export function corpusGeneratedAt(): string {
  return store.generated_at;
}

/** Counts by verdict, as written by the sweeper. */
export function corpusSummary(): Record<PackageVerdict, number> {
  return store.summary;
}

/** Total rows in the corpus. */
export function corpusSize(): number {
  return store.entries.length;
}

/** Every row. Callers must not mutate. */
export function corpusEntries(): readonly CorpusEntry[] {
  return store.entries;
}

/**
 * Rows worth showing on the public page: names that do not resolve to an
 * established package. Sorted so the ecosystem mix stays visible and the order
 * is stable across builds.
 */
export function flaggedEntries(): CorpusEntry[] {
  return store.entries
    .filter((e) => e.verdict === 'NONEXISTENT' || e.verdict === 'SLOPSQUAT_RISK')
    .sort((a, b) => {
      // Registered-but-unestablished names first: those are the live hazard,
      // because an install of one silently succeeds.
      if (a.verdict !== b.verdict) return a.verdict === 'SLOPSQUAT_RISK' ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
}

/** Corpus counts split by ecosystem, for the page's population breakdown. */
export function corpusByEcosystem(): Record<
  Ecosystem,
  Record<PackageVerdict, number>
> {
  const empty = (): Record<PackageVerdict, number> => ({
    EXISTS: 0,
    NONEXISTENT: 0,
    SLOPSQUAT_RISK: 0,
    UNKNOWN: 0,
  });
  const out = { npm: empty(), pypi: empty() };
  for (const e of store.entries) out[e.ecosystem][e.verdict] += 1;
  return out;
}
