import type { Metadata } from "next";
import Link from "next/link";
import { FirewallScanner } from "@/components/FirewallScanner";
import {
  corpusByEcosystem,
  corpusGeneratedAt,
  corpusSize,
  corpusSummary,
  flaggedEntries,
} from "@/lib/firewall/corpus-store";
import {
  ESTABLISHED_VERSION_COUNT,
  NEAR_ZERO_DOWNLOADS,
  YOUNG_PACKAGE_DAYS,
} from "@/lib/firewall/registry";

export const metadata: Metadata = {
  title: "Agent Dependency Firewall — Did Your Coding Agent Invent That Package? | MyMCPTools",
  description:
    "AI coding agents cite package names that do not exist, and attackers register them. Paste a package.json or requirements.txt and get a verdict per dependency, checked against the live npm and PyPI registries, with the evidence behind every verdict.",
  keywords:
    "slopsquatting, hallucinated packages, AI package hallucination, dependency confusion, npm typosquatting, agent security, package verification, supply chain security",
  openGraph: {
    title: "Agent Dependency Firewall — Did Your Coding Agent Invent That Package?",
    description:
      "Paste a dependency list. Get a verdict per package, checked against the live npm and PyPI registries, with the registry URL behind every verdict.",
    type: "website",
    url: "https://mymcptools.com/firewall",
    siteName: "MyMCPTools",
  },
  twitter: {
    card: "summary_large_image",
    title: "Agent Dependency Firewall — Did Your Coding Agent Invent That Package?",
    description:
      "AI coding agents cite packages that do not exist. Attackers register them. Check your dependency list against the live registries.",
  },
  alternates: { canonical: "https://mymcptools.com/firewall" },
};

const FAQ: { q: string; a: string }[] = [
  {
    q: "What is slopsquatting?",
    a: "An LLM recommends a package that does not exist. Somebody registers that name. The next developer whose agent recommends the same name installs the attacker's code. It works because hallucinated names are not random: across 576,000 code samples from 16 models, about 19.7% of recommended packages did not exist, and on repeated identical prompts 43% of hallucinated names came back every single run. A predictable wrong answer is a registrable one.",
  },
  {
    q: "Why does ordinary typosquatting detection not catch this?",
    a: "Typosquatting detection works by comparing a name to names that already exist — 'expres' is close to 'express', so it gets flagged. A hallucinated name is a novel string with nothing to collide against. There is no real package it is one character away from, so collision detection has nothing to compare it to and stays silent.",
  },
  {
    q: "What exactly does each verdict mean?",
    a: `EXISTS — the registry served a record for this exact name and it shows established-package markers. NONEXISTENT — the registry returned HTTP 404; the name resolves to nothing today, which also means it is available to register tomorrow. SLOPSQUAT_RISK — the registry served a record, but the package carries at least two independent unestablished-package markers, or self-declares as a defensive placeholder. UNKNOWN — we could not get a trustworthy answer from the registry. UNKNOWN is a real verdict here, not a placeholder: guessing would defeat the purpose of the tool.`,
  },
  {
    q: "Is SLOPSQUAT_RISK an accusation that a package is malicious?",
    a: `No, and it is worth being precise about this. It means the name resolves to something that is not an established package — a young publication, near-zero downloads, a single release, no source repository, or a description that self-identifies as a placeholder. Plenty of good packages are new. That is exactly why the rule requires two independent markers before it fires: any single marker on its own fires on ordinary healthy software, and a scanner that cries wolf gets turned off. Treat the verdict as "verify this by hand before an agent installs it", not as a finding.`,
  },
  {
    q: "Where does the corpus come from, and what is it not?",
    a: "Every row traces to an HTTP response we actually received from npm or PyPI, and each row records the URL that produced it so you can check our work. The names themselves currently come from two places: package names parsed out of install commands in this site's own MCP catalog, and names printed in published slopsquatting incident reporting. What the corpus is not, yet, is a record of what specific LLMs hallucinate — that requires farming model output nightly, which is the next build and is not represented here.",
  },
  {
    q: "Are these catalog names proof that an AI hallucinated them?",
    a: "No, and we will not claim it. A name in this corpus is a name some MCP directory listing asserted you should install. Whether any particular listing was written by a person, generated by a model, or copied from somewhere else is not established, and the corpus records only the provenance we can defend. What is demonstrable is the consequence: an agent that reads a directory and runs the install command it finds there will, most of the time, be installing a name that does not exist.",
  },
];

function pct(n: number, total: number): string {
  return total === 0 ? "0%" : `${Math.round((n / total) * 100)}%`;
}

export default function FirewallPage() {
  const summary = corpusSummary();
  const total = corpusSize();
  const byEco = corpusByEcosystem();
  const flagged = flaggedEntries();
  const generatedAt = corpusGeneratedAt().slice(0, 10);

  // The sample shown on the page: risky-but-registered names first, since those
  // are the ones an install silently succeeds on.
  const sample = flagged.slice(0, 60);

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd).replace(/</g, "\\u003c") }}
      />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-red-600/15 via-amber-600/10 to-blue-600/10" />
        <div className="relative mx-auto max-w-5xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-red-500/20 bg-red-500/10 px-4 py-1.5">
            <span className="h-2 w-2 animate-pulse rounded-full bg-red-400" aria-hidden="true" />
            <span className="text-sm font-medium text-red-400">
              Slopsquatting guard · checked against live registries
            </span>
          </div>
          <h1 className="mb-5 text-4xl font-bold leading-tight sm:text-5xl">
            Agent Dependency Firewall
          </h1>
          <p className="max-w-2xl text-lg leading-relaxed text-gray-400">
            AI coding agents recommend packages that do not exist. Roughly one in five
            recommended packages is invented, and the same invented names come back run after
            run — so attackers register them and wait. Your agent writes the import, the
            install succeeds, and nobody reads that line of the diff.
          </p>
          <p className="mt-4 max-w-2xl leading-relaxed text-gray-500">
            Paste a dependency list below. Every name is checked against the live npm or PyPI
            registry, and every verdict shows the registry URL it came from, so you can check
            our work rather than trust it.
          </p>
        </div>
      </section>

      <div className="mx-auto max-w-5xl px-4 pb-20 sm:px-6 lg:px-8">
        {/* The scanner */}
        <section id="scan">
          <FirewallScanner />
        </section>

        {/* Corpus population */}
        <section className="mt-14" id="corpus">
          <h2 className="mb-1 text-2xl font-bold text-gray-100">
            The corpus, and what is actually in it
          </h2>
          <p className="mb-6 text-sm text-gray-500">
            {total.toLocaleString()} package names, each checked against its live registry.
            Last full sweep {generatedAt}.
          </p>

          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            <div className="rounded-xl border border-gray-800 bg-gray-900/60 p-5">
              <div className="text-3xl font-bold text-red-400">
                {summary.NONEXISTENT.toLocaleString()}
              </div>
              <div className="mt-1 text-sm text-gray-400">
                Do not exist ({pct(summary.NONEXISTENT, total)})
              </div>
            </div>
            <div className="rounded-xl border border-gray-800 bg-gray-900/60 p-5">
              <div className="text-3xl font-bold text-amber-400">
                {summary.SLOPSQUAT_RISK.toLocaleString()}
              </div>
              <div className="mt-1 text-sm text-gray-400">
                Registered but unestablished
              </div>
            </div>
            <div className="rounded-xl border border-gray-800 bg-gray-900/60 p-5">
              <div className="text-3xl font-bold text-emerald-400">
                {summary.EXISTS.toLocaleString()}
              </div>
              <div className="mt-1 text-sm text-gray-400">Established packages</div>
            </div>
            <div className="rounded-xl border border-gray-800 bg-gray-900/60 p-5">
              <div className="text-3xl font-bold text-gray-500">
                {summary.UNKNOWN.toLocaleString()}
              </div>
              <div className="mt-1 text-sm text-gray-400">No trustworthy answer</div>
            </div>
          </div>

          <div className="mt-4 rounded-xl border border-gray-800 bg-gray-900/40 p-5 text-sm leading-relaxed text-gray-400">
            <p>
              These names were parsed out of the install commands of entries in this site&apos;s
              own MCP catalog — the exact strings an agent would run{" "}
              <code className="font-mono text-xs text-gray-300">npx</code> or{" "}
              <code className="font-mono text-xs text-gray-300">pip install</code> against after
              reading a directory listing. Of{" "}
              <strong className="text-gray-200">{total.toLocaleString()}</strong> distinct names,{" "}
              <strong className="text-gray-200">{summary.NONEXISTENT.toLocaleString()}</strong>{" "}
              returned HTTP 404 from the registry.
            </p>
            <p className="mt-3">
              We are not claiming a model invented each of those. The provenance we can defend is
              narrower and still damning: a directory said to install them, and the registry says
              they are not there. npm accounts for{" "}
              {byEco.npm.NONEXISTENT.toLocaleString()} of the 404s across{" "}
              {(
                byEco.npm.EXISTS +
                byEco.npm.NONEXISTENT +
                byEco.npm.SLOPSQUAT_RISK +
                byEco.npm.UNKNOWN
              ).toLocaleString()}{" "}
              npm names; PyPI accounts for {byEco.pypi.NONEXISTENT.toLocaleString()} across{" "}
              {(
                byEco.pypi.EXISTS +
                byEco.pypi.NONEXISTENT +
                byEco.pypi.SLOPSQUAT_RISK +
                byEco.pypi.UNKNOWN
              ).toLocaleString()}{" "}
              PyPI names.
            </p>
            <p className="mt-3">
              What this corpus does <strong className="text-gray-200">not</strong> yet contain is
              a record of what specific models hallucinate. Published research counts 53 names
              still unregistered across five frontier models, but reports the count without
              printing the list — so those names are absent here rather than guessed at. Farming
              model output nightly is the next build, and it is the part that turns this from a
              checker into a threat feed.
            </p>
          </div>
        </section>

        {/* Verdict rules */}
        <section className="mt-14" id="rules">
          <h2 className="mb-1 text-2xl font-bold text-gray-100">How a verdict is reached</h2>
          <p className="mb-6 text-sm text-gray-500">
            The thresholds are fixed and public, so you can disagree with them without having to
            take the verdict on faith. Only a completed HTTP response can produce a verdict.
          </p>
          <ul className="divide-y divide-gray-800 rounded-xl border border-gray-800 bg-gray-900/40 px-5">
            {[
              [
                "NONEXISTENT",
                "Registry returned HTTP 404 for the exact name. A build depending on it cannot install — and the name is free for anyone to take.",
              ],
              [
                "SLOPSQUAT_RISK",
                `Registry returned 200, but the record self-declares as a placeholder, or carries two or more independent unestablished markers: first published under ${YOUNG_PACKAGE_DAYS} days ago, ${NEAR_ZERO_DOWNLOADS} or fewer weekly downloads, a single published version, or no declared source repository.`,
              ],
              [
                "EXISTS",
                `Registry returned 200 and the record clears the risk rules — in practice, ${ESTABLISHED_VERSION_COUNT} or more published versions without near-zero downloads, or fewer than two risk markers.`,
              ],
              [
                "UNKNOWN",
                "No completed, trustworthy response — a timeout, a 5xx, or a name that is not addressable as a package name at all. Never inferred from anything, and never cached.",
              ],
            ].map(([verdict, detail]) => (
              <li key={verdict} className="flex flex-col gap-1 py-4 sm:flex-row sm:gap-5">
                <div className="sm:w-44 sm:shrink-0">
                  <code className="font-mono text-sm font-medium text-gray-200">{verdict}</code>
                </div>
                <p className="text-sm leading-relaxed text-gray-400">{detail}</p>
              </li>
            ))}
          </ul>
          <p className="mt-4 text-sm leading-relaxed text-gray-500">
            One measurement gap, stated rather than hidden: PyPI&apos;s JSON API does not serve
            download counts, and the third-party service that does rate-limited us on first
            contact. The near-zero-downloads marker is therefore npm-only, and PyPI verdicts rest
            on publication age, release count and repository presence. That makes PyPI risk
            detection weaker than npm&apos;s, not equivalent to it.
          </p>
        </section>

        {/* Sample of flagged names */}
        <section className="mt-14" id="flagged">
          <h2 className="mb-1 text-2xl font-bold text-gray-100">
            A sample of what came back flagged
          </h2>
          <p className="mb-6 text-sm text-gray-500">
            {sample.length} of {flagged.length.toLocaleString()} flagged names. Registered-but-unestablished
            first — those are the live hazard, because installing one silently succeeds.
          </p>
          <ul className="divide-y divide-gray-800 rounded-xl border border-gray-800 bg-gray-900/40">
            {sample.map((e) => (
              <li
                key={`${e.ecosystem}:${e.name}`}
                className="flex flex-wrap items-center gap-3 px-5 py-3"
              >
                <code className="font-mono text-sm text-gray-200">{e.name}</code>
                <span className="rounded border border-gray-700 px-1.5 py-0.5 font-mono text-xs text-gray-500">
                  {e.ecosystem}
                </span>
                <span
                  className={`rounded-full border px-2.5 py-0.5 text-xs font-medium ${
                    e.verdict === "NONEXISTENT"
                      ? "border-red-500/30 bg-red-500/10 text-red-300"
                      : "border-amber-500/30 bg-amber-500/10 text-amber-300"
                  }`}
                >
                  {e.verdict === "NONEXISTENT" ? "404" : "unestablished"}
                </span>
                {e.markers.length > 0 && (
                  <span className="text-xs text-gray-600">
                    {e.markers.map((m) => m.id).join(" · ")}
                  </span>
                )}
              </li>
            ))}
          </ul>
        </section>

        {/* API CTA */}
        <section className="mt-14 rounded-2xl border border-gray-800 bg-gradient-to-br from-red-600/10 to-blue-600/5 p-8">
          <h2 className="text-xl font-bold text-gray-100">Gate this in CI</h2>
          <p className="mt-2 max-w-2xl text-sm leading-relaxed text-gray-400">
            The same engine is available as an authenticated endpoint on the Trust Data API —
            POST a list of names and an ecosystem, get a verdict and its evidence per name, and
            fail the build when anything comes back NONEXISTENT.
          </p>
          <pre className="mt-5 overflow-x-auto rounded-xl border border-gray-800 bg-gray-950/70 p-4 font-mono text-xs leading-relaxed text-gray-300">
{`curl -X POST https://mymcptools.com/api/v1/firewall/check \\
  -H "Authorization: Bearer $MCPTOOLS_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"ecosystem":"npm","packages":["express","react-codeshift"]}'`}
          </pre>
          <p className="mt-4 text-sm text-gray-500">
            A GitHub Action and an installable CLI are the next surfaces and do not exist yet.
            The endpoint above does.
          </p>
          <div className="mt-5 flex flex-wrap gap-3">
            <Link
              href="/developers"
              className="inline-flex items-center rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-700"
            >
              Get an API key
            </Link>
            <Link
              href="/trust"
              className="inline-flex items-center rounded-xl border border-gray-700 px-5 py-3 text-sm font-semibold text-gray-200 transition hover:bg-gray-800"
            >
              See the MCP Trust Registry
            </Link>
          </div>
        </section>

        {/* FAQ */}
        <section className="mt-14">
          <h2 className="mb-6 text-2xl font-bold text-gray-100">Dependency Firewall FAQ</h2>
          <div className="space-y-4">
            {FAQ.map((f) => (
              <div key={f.q} className="rounded-xl border border-gray-800 bg-gray-900/40 p-5">
                <h3 className="mb-2 font-semibold text-gray-100">{f.q}</h3>
                <p className="text-sm leading-relaxed text-gray-400">{f.a}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
