// Read-side accessor for the committed probe-status.json store (PRD P0-5/P0-7).
// The file is the build-time source of truth for every v1 API response; it is
// regenerated by the prober and committed, so a static import is correct and
// gives fast, allocation-free reads.

import rawStore from "@/data/probe-status.json";
import { VERDICTS } from "@/lib/trust/types";
import type { CurrentStatus, StatusStore, Verdict } from "@/lib/trust/types";

const store = rawStore as StatusStore;

/**
 * The committed store carries duplicate slugs — on the 2026-08-12 file, 2,726
 * rows over 2,440 distinct servers (201 slugs appear more than once). `bySlug`
 * has always collapsed those, so `getStatus` was right while every count taken
 * off `store.statuses`/`store.summary` was inflated by ~11%: the /status page,
 * `/api/v1/status`, `/api/v1/export`, `get_catalog_stats` and `total_tracked`
 * all reported more servers than the catalog holds (2,467), and the duplicates
 * are overwhelmingly UNPROBEABLE, so they also skewed the verdict mix.
 *
 * Deduplicate once here, last row wins, matching what `bySlug`/`getStatus`
 * already serve. Every read-side consumer then agrees on one population.
 */
const bySlug = new Map<string, CurrentStatus>(
  store.statuses.map((s) => [s.slug, s])
);

const dedupedStatuses: readonly CurrentStatus[] = Array.from(bySlug.values());

const dedupedSummary: Record<Verdict, number> = (() => {
  const counts = {} as Record<Verdict, number>;
  for (const v of VERDICTS) counts[v] = 0;
  for (const s of dedupedStatuses) counts[s.verdict] = (counts[s.verdict] ?? 0) + 1;
  return counts;
})();

/** When the committed dataset was generated. */
export function generatedAt(): string {
  return store.generated_at;
}

/** The whole committed status store (do not mutate) — e.g. as a corroborating
 * input to the digest for last_seen_good_at. */
export function statusStore(): StatusStore {
  return store;
}

/** Verdict counts across the whole inventory, one row per slug. */
export function summary(): Record<Verdict, number> {
  return dedupedSummary;
}

/** Every current_status row, one per slug (do not mutate). */
export function allStatuses(): readonly CurrentStatus[] {
  return dedupedStatuses;
}

/** One server's current_status, or undefined for an unknown slug. */
export function getStatus(slug: string): CurrentStatus | undefined {
  return bySlug.get(slug);
}
