// Read-side accessor for the committed probe-status.json store (PRD P0-5/P0-7).
// The file is the build-time source of truth for every v1 API response; it is
// regenerated by the prober and committed, so a static import is correct and
// gives fast, allocation-free reads.

import rawStore from "@/data/probe-status.json";
import type { CurrentStatus, StatusStore, Verdict } from "@/lib/trust/types";

const store = rawStore as StatusStore;

const bySlug = new Map<string, CurrentStatus>(
  store.statuses.map((s) => [s.slug, s])
);

/** When the committed dataset was generated. */
export function generatedAt(): string {
  return store.generated_at;
}

/** Verdict counts across the whole inventory. */
export function summary(): Record<Verdict, number> {
  return store.summary;
}

/** Every current_status row (do not mutate). */
export function allStatuses(): readonly CurrentStatus[] {
  return store.statuses;
}

/** One server's current_status, or undefined for an unknown slug. */
export function getStatus(slug: string): CurrentStatus | undefined {
  return bySlug.get(slug);
}
