// Read-side accessor for the committed static-signals.json store (PRD P1-3).
// Local/stdio servers carry no remote endpoint and are recorded UNPROBEABLE by
// the prober; this store supplies the *static* freshness signal (last commit /
// last release from their GitHub repo) that listings show in place of a live
// verdict. The file is regenerated by scripts/static-signals.mts and committed,
// so a static import is correct and gives fast, allocation-free reads.

import rawStore from "@/data/static-signals.json";
import type { StaticSignal, StaticSignalStore } from "@/lib/trust/types";

const store = rawStore as StaticSignalStore;

const SIX_MONTHS_MS = 1000 * 60 * 60 * 24 * 30 * 6;
const EIGHTEEN_MONTHS_MS = 1000 * 60 * 60 * 24 * 30 * 18;

/** Coarse freshness bucket from the most recent of commit/release dates. */
function deriveFreshness(s: StaticSignal): StaticSignal["freshness"] {
  const dates = [s.last_commit_at, s.last_release_at]
    .map((d) => (d ? new Date(d).getTime() : NaN))
    .filter((t) => !Number.isNaN(t));
  if (dates.length === 0) return "unknown";
  const age = Date.now() - Math.max(...dates);
  if (age <= SIX_MONTHS_MS) return "active";
  if (age <= EIGHTEEN_MONTHS_MS) return "aging";
  return "stale";
}

const bySlug = new Map<string, StaticSignal>(
  store.signals.map((s) => [s.slug, { ...s, freshness: deriveFreshness(s) }])
);

/** One server's static signal (with derived freshness), or undefined. */
export function getStaticSignal(slug: string): StaticSignal | undefined {
  return bySlug.get(slug);
}

/** When the committed static-signals dataset was generated. */
export function staticSignalsGeneratedAt(): string {
  return store.generated_at;
}
